import img1 from '../assets/img-1.jpg';
import img2 from '../assets/img-2.jpg';
import img3 from '../assets/img-3.jpg';
import img4 from '../assets/img-4.jpg';
import img5 from '../assets/img-5.jpg';
import img6 from '../assets/img-6.jpg';
import img7 from '../assets/img-7.jpg';
import img8 from '../assets/img-8.jpg';
import img9 from '../assets/img-9.jpeg';
import img10 from '../assets/img-10.jpeg';
import img11 from '../assets/img-11.jpeg';
import img12 from '../assets/img-12.jpeg';
import img13 from '../assets/img-13.jpeg';
import img14 from '../assets/img-14.jpeg';

export const tours = [
  {
    id: 1,
    image: img1,
    date: 'november 12th, 2023',
    title: `trails & gems of siam`,
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'thailand',
    continent: 'asia',
    tags: 'bangkok, chiangmai',
    cost: '1000',
    duration: '12 days',
  },
  {
    id: 2,
    image: img2,
    date: 'september 25th, 2023',
    title: `history of the caribbean`,
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'santo domingo',
    continent: 'south america',
    tags: 'dominican republic',
    cost: '900',
    duration: '7 days',
  },
  {
    id: 3,
    image: img3,
    date: 'july 23rd, 2023',
    title: `tapas, taverns, & history`,
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'madrid',
    continent: 'europe',
    tags: 'spain',
    cost: '1800',
    duration: '14 days',
  },
  {
    id: 4,
    image: img4,
    date: 'february 22nd, 2023',
    title: `highlights of croatia`,
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'croatia',
    continent: 'europe',
    tags: 'zagreb',
    cost: '3400',
    duration: '12 days',
  },
  {
    id: 5,
    image: img5,
    date: 'may 4th, 2023',
    title: `athens & island hopping`,
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'greece',
    continent: 'europe',
    tags: 'athens, greek',
    cost: '2100',
    duration: '10 days',
  },
  {
    id: 6,
    image: img6,
    date: 'may 30th, 2023',
    title: `mexico unplugged`,
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'tulum',
    continent: 'south america',
    tags: 'mexico',
    cost: '1600',
    duration: '15 days',
  },
  {
    id: 7,
    image: img7,
    date: 'march 14th, 2023',
    title: `highlights of seoul & busan`,
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'south korea',
    continent: 'asia',
    tags: 'seoul, busan, korea',
    cost: '2100',
    duration: '14 days',
  },
  {
    id: 8,
    image: img8,
    date: 'january 28th, 2023',
    title: 'machu picchu & the andes',
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'peru',
    continent: 'south america',
    tags: 'andes, lima, cuzco, cusco',
    cost: '1600',
    duration: '14 days',
  },
  {
    id: 9,
    image: img9,
    date: 'august 26th, 2022',
    title: 'tibet adventures',
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'tibet',
    continent: 'asia',
    tags: 'china',
    cost: '1300',
    duration: '7 days',
  },
  {
    id: 10,
    image: img10,
    date: 'may 15th, 2022',
    title: 'splendors of south africa',
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'south africa',
    continent: 'africa',
    tags: 'cape town',
    cost: '2000',
    duration: '15 days',
  },
  {
    id: 11,
    image: img11,
    date: 'november 23rd, 2022',
    title: `world treasures of india`,
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'india',
    continent: 'asia',
    tags: 'delhi',
    cost: '1200',
    duration: '7 days',
  },
  {
    id: 12,
    image: img12,
    date: 'october 11th, 2022',
    title: 'best of java in bali',
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'indonesia',
    continent: 'asia',
    tags: 'bali',
    cost: '900',
    duration: '11 days',
  },
  {
    id: 13,
    image: img13,
    date: 'september 15th, 2022',
    title: 'essence of macau',
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'hong kong',
    continent: 'asia',
    tags: 'china',
    cost: '1200',
    duration: '8 days',
  },
  {
    id: 14,
    image: img14,
    date: 'december 5th, 2022',
    title: 'kenya adventures',
    info: `Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cumque vitae tempore voluptatum maxime reprehenderit eum quod exercitationem fugit, qui corporis.`,
    location: 'kenya',
    continent: 'africa',
    tags: 'nairobi',
    cost: '1300',
    duration: '16 days',
  },
];
